name: Nest Snowflake Id

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      NEW_PACKAGE_VERSION: ${{ github.event.release.tag_name }}
      NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          scope: '@street-devs'
      - run: npm ci
      - run: npm run build
      - run: npm run increase-version
      - run: npm publish
